/*
 * Copyright (C) 2025 ModSeeker
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.example.modseeker;

import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.entity.Player;
import org.bukkit.scheduler.BukkitRunnable;

import java.util.UUID;

/**
 * Manages the handshake process between the server and the client mod.
 */
public class HandshakeManager {

    private final ModSeekerPlugin plugin;
    private final PlayerDataManager playerDataManager;
    private final MessageHandler messageHandler;
    private final ModListParser modListParser;
    private final ConfigManager configManager;
    private final VerificationService verificationService;
    private final LauncherVerifier launcherVerifier;
    private final SecurityManager securityManager;

    // PLACEHOLDER: Replace with the value from HMAC_SECRET_JAVA.txt (generated by Tools/KeyGen.java)
    // Must be identical to the HMAC_SECRET in SecurityManager.java and the key in hidder_vault.cpp
    private static final String HMAC_SECRET = "REPLACE_WITH_HMAC_SECRET_FROM_KEYGEN";

    public HandshakeManager(ModSeekerPlugin plugin, PlayerDataManager playerDataManager,
            MessageHandler messageHandler, ModListParser modListParser,
            ConfigManager configManager, VerificationService verificationService,
            LauncherVerifier launcherVerifier, SecurityManager securityManager) {
        this.plugin = plugin;
        this.playerDataManager = playerDataManager;
        this.messageHandler = messageHandler;
        this.modListParser = modListParser;
        this.configManager = configManager;
        this.verificationService = verificationService;
        this.launcherVerifier = launcherVerifier;
        this.securityManager = securityManager;
    }

    /**
     * Starts the handshake process for a player.
     * 
     * @param player The player to handshake with.
     */
    public void startHandshake(Player player) {
        UUID playerId = player.getUniqueId();
        String playerName = player.getName();

        PlayerDataManager.HandshakeData handshakeData = new PlayerDataManager.HandshakeData(playerId, playerName);
        playerDataManager.getPlayerHandshakes().put(playerId, handshakeData);

        String playerIP = player.getAddress() != null ? player.getAddress().getAddress().getHostAddress() : "unknown";
        plugin.logInfo("🌍 Player Join: " + playerName + " (UUID: " + playerId.toString() + ", IP: " + playerIP + ")");
        plugin.logInfo("🤝 Handshake started [ID: " + handshakeData.handshakeId + "]");

        // Discord webhook - player join
        plugin.getDiscordWebhook().sendPlayerJoin(playerName, playerId.toString(), playerIP);

        messageHandler.sendHandshakeRequest(player);

        startHandshakeTimeoutTimer(player, handshakeData);
    }

    /**
     * Handles the ANNOUNCE_PRESENCE message from the client.
     * 
     * @param player      The player who sent the message.
     * @param messageJson The JSON message content.
     */
    public void handleAnnouncePresence(Player player, String messageJson) {
        UUID playerId = player.getUniqueId();
        String playerName = player.getName();
        PlayerDataManager.HandshakeData handshakeData = playerDataManager.getPlayerHandshakes().get(playerId);

        if (handshakeData == null) {
            return;
        }

        handshakeData.presenceAnnounced = true;
        handshakeData.presenceMessage = messageJson;

        if (messageJson.contains("\"modId\":\"" + ProtocolConstants.HIDDER_MOD_ID + "\"")) {
            plugin.logInfo("✅ Hidder presence confirmed");

            String version = modListParser.extractModVersion(messageJson);
            if (version != null) {
                handshakeData.modVersion = version;
            }

            // Layer 1: Send HMAC challenge for launcher verification (only if enabled)
            if (configManager.isLauncherVerificationEnabled()) {
                sendChallenge(player, handshakeData);
            } else {
                sendAcknowledgePresence(player, handshakeData);
            }

        } else {
            plugin.logInfo("❌ Invalid mod detected for player " + playerName);
            handshakeData.presenceAnnounced = false;
        }
    }

    private void sendAcknowledgePresence(Player player, PlayerDataManager.HandshakeData handshakeData) {
        try {
            if (handshakeData.timeoutTaskId != -1) {
                Bukkit.getScheduler().cancelTask(handshakeData.timeoutTaskId);
                handshakeData.timeoutTaskId = -1;
            }

            if (handshakeData.presenceTimeoutTaskId != -1) {
                Bukkit.getScheduler().cancelTask(handshakeData.presenceTimeoutTaskId);
                handshakeData.presenceTimeoutTaskId = -1;
            }

            String ackJson = "{\"messageType\":\"" + ProtocolConstants.MSG_ACKNOWLEDGE_PRESENCE
                    + "\",\"status\":\"ready\",\"serverId\":\"" + ProtocolConstants.PLUGIN_VERSION + "\"}";

            messageHandler.sendPluginMessage(player, ackJson);

            handshakeData.acknowledgmentSent = true;

            // Layer 3: Only start modlist check if ModVerification is enabled
            if (configManager.isModVerificationEnabled()) {
                verificationService.startModCheckAfterHandshake(player, handshakeData);
            } else {
                // ModVerification off — skip Layer 3, approve player
                plugin.logInfo("⚠️ Layer 3 disabled (ModVerification: false) — skipping modlist check");
                playerDataManager.addApprovedPlayer(player.getUniqueId());
                securityManager.unfreezePlayer(player.getUniqueId());
                if (configManager.isEnablePlayerNotifications()) {
                    player.sendMessage(org.bukkit.ChatColor.GREEN + configManager.getWelcomeMessage());
                }
            }

        } catch (Exception e) {
            plugin.logInfo("❌ FAILED TO SEND ACKNOWLEDGMENT to " + handshakeData.playerName + ": " + e.getMessage());
            player.kickPlayer(ChatColor.RED + "Handshake failed.");
        }
    }

    private void startHandshakeTimeoutTimer(Player player, PlayerDataManager.HandshakeData handshakeData) {
        BukkitRunnable timeoutTask = new BukkitRunnable() {
            @Override
            public void run() {
                // Check if player is still in handshake process and hasn't announced presence
                if (playerDataManager.getPlayerHandshakes().containsKey(handshakeData.playerId)
                        && !handshakeData.presenceAnnounced) {
                    // Try to get the player object again in case the original reference is invalid
                    Player currentPlayer = Bukkit.getPlayer(handshakeData.playerId);
                    if (currentPlayer != null && currentPlayer.isOnline()) {
                        handleHandshakeTimeout(currentPlayer, handshakeData);
                    } else {
                        handleHandshakeTimeoutOffline(handshakeData);
                    }
                }
            }
        };

        handshakeData.presenceTimeoutTaskId = timeoutTask
                .runTaskLater(plugin, 100L).getTaskId();
    }

    private void handleHandshakeTimeoutOffline(PlayerDataManager.HandshakeData handshakeData) {
        // Remove the handshake data to prevent further processing
        playerDataManager.getPlayerHandshakes().remove(handshakeData.playerId);

        // Log handshake timeout scenario
        plugin.logInfo("⚠️ Hidder presence unable to confirmed");
        plugin.logInfo("❌Player verification incomplete — access denied");
        plugin.logInfo("🦵 " + handshakeData.playerName + " has been kicked from the server for not having Hidder");
    }

    private void handleHandshakeTimeout(Player player, PlayerDataManager.HandshakeData handshakeData) {
        // Check if the player is still in the handshake process
        if (!playerDataManager.getPlayerHandshakes().containsKey(handshakeData.playerId)) {
            return; // Player already completed handshake or left the game
        }

        // Remove the handshake data to prevent further processing
        playerDataManager.getPlayerHandshakes().remove(handshakeData.playerId);

        // Log handshake timeout scenario
        plugin.logInfo("⚠️ Hidder presence unable to confirmed");
        plugin.logInfo("❌Player verification incomplete — access denied");
        plugin.logInfo("🦵 " + handshakeData.playerName + " has been kicked from the server for not having Hidder");

        String kickMessage = configManager.getKickMessages().getOrDefault("missingHidder",
                "Please Install Hidder Mod To Enter The Server");
        player.kickPlayer(ChatColor.RED + kickMessage);
    }

    /**
     * Cleans up handshake data for a player.
     * 
     * @param playerId The UUID of the player.
     * @return The handshake data that was removed, or null if none existed.
     */
    public PlayerDataManager.HandshakeData cleanupHandshakeData(UUID playerId) {
        PlayerDataManager.HandshakeData data = playerDataManager.getPlayerHandshakes().remove(playerId);
        if (data != null) {
            if (data.timeoutTaskId != -1) {
                Bukkit.getScheduler().cancelTask(data.timeoutTaskId);
            }
            if (data.presenceTimeoutTaskId != -1) {
                Bukkit.getScheduler().cancelTask(data.presenceTimeoutTaskId);
            }
        }
        return data;
    }

    public void sendChallenge(Player player, PlayerDataManager.HandshakeData handshakeData) {
        // Cancel presence timeout — presence was already confirmed
        if (handshakeData.presenceTimeoutTaskId != -1) {
            Bukkit.getScheduler().cancelTask(handshakeData.presenceTimeoutTaskId);
            handshakeData.presenceTimeoutTaskId = -1;
        }
        if (handshakeData.timeoutTaskId != -1) {
            Bukkit.getScheduler().cancelTask(handshakeData.timeoutTaskId);
            handshakeData.timeoutTaskId = -1;
        }

        // Defer challenge send to next tick — sending plugin messages from within
        // onPluginMessageReceived callback can be silently dropped
        new BukkitRunnable() {
            @Override
            public void run() {
                if (!player.isOnline()) return;

                String nonce = generateNonce();
                long timestamp = System.currentTimeMillis();

                handshakeData.challengeNonce = nonce;
                handshakeData.challengeTimestamp = timestamp;

                String challengeJson = "{\"messageType\":\"" + ProtocolConstants.MSG_CHALLENGE +
                        "\",\"nonce\":\"" + nonce + "\",\"timestamp\":" + timestamp + "}";

                messageHandler.sendPluginMessage(player, challengeJson);
            }
        }.runTaskLater(plugin, 1L);

        // Start challenge response timeout
        BukkitRunnable challengeTimeout = new BukkitRunnable() {
            @Override
            public void run() {
                if (playerDataManager.getPlayerHandshakes().containsKey(handshakeData.playerId)
                        && !handshakeData.challengePassed) {
                    Player currentPlayer = Bukkit.getPlayer(handshakeData.playerId);
                    if (currentPlayer != null && currentPlayer.isOnline()) {
                        currentPlayer.kickPlayer("§cLauncher verification timed out. Please try again.");
                    }
                    playerDataManager.getPlayerHandshakes().remove(handshakeData.playerId);
                }
            }
        };
        handshakeData.timeoutTaskId = challengeTimeout
                .runTaskLater(plugin, 100L).getTaskId();
    }

    public void handleChallengeResponse(Player player, String messageJson) {
        UUID playerId = player.getUniqueId();
        PlayerDataManager.HandshakeData handshakeData = playerDataManager.getPlayerHandshakes().get(playerId);

        if (handshakeData == null) {
            return;
        }

        try {
            // Parse JSON manually (no Gson dependency in this project)
            String hmac = extractJsonStringValue(messageJson, ProtocolConstants.KEY_HMAC);
            String launcherId = extractJsonStringValue(messageJson, ProtocolConstants.KEY_LAUNCHER_ID);
            String launcherName = extractJsonStringValue(messageJson, ProtocolConstants.KEY_LAUNCHER_NAME);

            if (launcherId == null || launcherId.isEmpty()) {
                launcherId = "unknown";
            }
            if (launcherName == null || launcherName.isEmpty()) {
                launcherName = "Unknown";
            }

            long responseTime = System.currentTimeMillis() - handshakeData.challengeTimestamp;
            if (responseTime > 5000) {
                player.kickPlayer("§cChallenge response too slow. Please try again.");
                return;
            }

            String expectedData = handshakeData.challengeNonce + handshakeData.challengeTimestamp;

            // Check for client-side error codes before HMAC verification
            if (hmac != null) {
                if (hmac.equals("DLL_NOT_LOADED")) {
                    plugin.logInfo("❌ Layer 1: Client " + handshakeData.playerName + " native DLL not loaded");
                    player.kickPlayer("§cSecurity Error: Mod installation incomplete.\n§7Reinstall the mod pack.");
                    return;
                }
                if (hmac.equals("CLIENT_ERROR")) {
                    plugin.logInfo("❌ Layer 1: Client error for " + handshakeData.playerName + ": " + launcherName);
                    player.kickPlayer("§cSecurity Error: Client error.\n§7Check client logs.");
                    return;
                }
            }

            if (!verifyHmac(expectedData, hmac)) {
                plugin.logInfo("❌ Layer 1: Invalid HMAC from " + handshakeData.playerName);
                player.kickPlayer("§cInvalid client verification.");
                return;
            }

            launcherVerifier.logLauncherDetected(handshakeData.playerName, launcherId);

            if (!launcherVerifier.isLauncherAllowed(launcherId)) {
                launcherVerifier.kickForInvalidLauncher(player, launcherId);
                return;
            }

            handshakeData.challengePassed = true;

            sendAcknowledgePresence(player, handshakeData);

        } catch (Exception e) {
            plugin.logInfo("❌ Layer 1: Error processing challenge response: " + e.getMessage());
            player.kickPlayer("§cVerification failed.");
        }
    }

    /**
     * Extract a string value from JSON manually (no Gson dependency)
     */
    private String extractJsonStringValue(String json, String key) {
        String searchKey = "\"" + key + "\":\"";
        int startIndex = json.indexOf(searchKey);
        if (startIndex == -1) return null;
        startIndex += searchKey.length();
        int endIndex = json.indexOf("\"", startIndex);
        if (endIndex == -1) return null;
        return json.substring(startIndex, endIndex);
    }

    private String generateNonce() {
        byte[] bytes = new byte[16];
        new java.security.SecureRandom().nextBytes(bytes);
        StringBuilder sb = new StringBuilder();
        for (byte b : bytes) {
            sb.append(String.format("%02x", b));
        }
        return sb.toString();
    }

    private boolean verifyHmac(String data, String receivedHmac) {
        if (receivedHmac == null || receivedHmac.isEmpty()) {
            return false;
        }

        try {
            javax.crypto.Mac mac = javax.crypto.Mac.getInstance("HmacSHA256");
            javax.crypto.spec.SecretKeySpec keySpec = new javax.crypto.spec.SecretKeySpec(
                    HMAC_SECRET.getBytes(), "HmacSHA256");
            mac.init(keySpec);

            byte[] hmacBytes = mac.doFinal(data.getBytes());
            String expectedHmac = java.util.Base64.getEncoder().encodeToString(hmacBytes);

            return expectedHmac.equals(receivedHmac);
        } catch (Exception e) {
            return false;
        }
    }
}
