/*
 * Copyright (C) 2025 ModSeeker
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.example.modseeker;

import java.nio.charset.StandardCharsets;
import java.security.KeyFactory;
import java.security.PublicKey;
import java.security.Signature;
import java.security.spec.X509EncodedKeySpec;
import java.util.Base64;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.event.block.BlockPlaceEvent;
import org.bukkit.event.entity.EntityDamageByEntityEvent;
import org.bukkit.event.entity.EntityDamageEvent;
import org.bukkit.event.player.AsyncPlayerPreLoginEvent;
import org.bukkit.event.player.PlayerCommandPreprocessEvent;
import org.bukkit.event.player.PlayerDropItemEvent;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.event.player.PlayerMoveEvent;

import com.destroystokyo.paper.event.server.PaperServerListPingEvent;
import java.net.InetSocketAddress;

/**
 * Manages security functions including:
 * - Layer 0: Pre-login beacon cache with DDoS protection
 * - Layer 1: Player freeze during verification
 * - Layer 2+3: Signature verification and replay attack protection
 */
public class SecurityManager implements Listener {

    private final ModSeekerPlugin plugin;
    private PublicKey publicKey;
    private boolean validationEnabled = false;

    // ============================================================
    // Layer 0: Pre-Login Beacon Cache (with DDoS protection)
    // ============================================================
    private final Map<String, Long> verifiedIPs = new ConcurrentHashMap<>();
    private final Map<String, Long> rateLimitMap = new ConcurrentHashMap<>();
    private static final long BEACON_EXPIRY_MS = 30_000; // 30 seconds
    private static final int BEACON_MAX_SIZE = 1000; // Max 1000 entries
    private static final long BEACON_RATE_LIMIT_MS = 5_000; // 5 seconds between pings per IP

    // TEMPORARY: Disable Layer 0 until mixin is fixed for 1.21.11
    private static final boolean LAYER_0_ENABLED = false;

    // ============================================================
    // Layer 1: Player Freeze
    // ============================================================
    private final Set<UUID> frozenPlayers = ConcurrentHashMap.newKeySet();

    private static final String BEACON_PREFIX = "HIDDER_BEACON:";
    private ConfigManager configManager;

    // Shared HMAC secret — must match the key in hidder_vault.dll
    // PLACEHOLDER: Replace with the value from HMAC_SECRET_JAVA.txt (generated by Tools/KeyGen.java)
    private static final String HMAC_SECRET = "REPLACE_WITH_HMAC_SECRET_FROM_KEYGEN";

    // Public key for verifying signatures (corresponds to private key in Hidder mod)
    // PLACEHOLDER: Replace with the value from SERVER_VERIFY_KEY.txt (generated by Tools/KeyGen.java)
    private static final String DEFAULT_PUBLIC_KEY = "REPLACE_WITH_CLIENT_PUBLIC_KEY_FROM_KEYGEN";

    // Server Private Key for Decryption
    // PLACEHOLDER: Replace with the value from SERVER_KEY_JAVA.txt (generated by Tools/KeyGen.java)
    private static final String SERVER_PRIVATE_KEY = "REPLACE_WITH_SERVER_PRIVATE_KEY_FROM_KEYGEN";

    private java.security.PrivateKey privateKey;

    public SecurityManager(ModSeekerPlugin plugin) {
        this.plugin = plugin;
        loadPublicKey();
        loadPrivateKey();
        // Events are registered by ModSeekerPlugin.onEnable() — do NOT self-register here
    }

    private void loadPrivateKey() {
        try {
            byte[] keyBytes = Base64.getDecoder().decode(SERVER_PRIVATE_KEY);
            java.security.spec.PKCS8EncodedKeySpec spec = new java.security.spec.PKCS8EncodedKeySpec(keyBytes);
            KeyFactory kf = KeyFactory.getInstance("RSA");
            this.privateKey = kf.generatePrivate(spec);
        } catch (Exception e) {
            plugin.logInfo("❌ Security: Failed to load private key: " + e.getMessage());
        }
    }

    public String decrypt(String ciphertext) {
        try {
            String[] parts = ciphertext.split("\\|");

            if (parts.length != 3) {
                plugin.logInfo("❌ Security: Invalid ciphertext format. Expected 3 parts, got " + parts.length);
                return null;
            }

            String encKeyB64 = parts[0];
            String ivB64 = parts[1];
            String encDataB64 = parts[2];

            byte[] decodedKeyBytes = Base64.getMimeDecoder().decode(encKeyB64);

            if (decodedKeyBytes.length > 256) {
                plugin.logInfo("❌ Security: Invalid encrypted key length: " + decodedKeyBytes.length);
                return null;
            }

            javax.crypto.Cipher rsaCipher = javax.crypto.Cipher.getInstance("RSA/ECB/PKCS1Padding");
            rsaCipher.init(javax.crypto.Cipher.DECRYPT_MODE, privateKey);
            byte[] aesKey = rsaCipher.doFinal(decodedKeyBytes);

            javax.crypto.Cipher aesCipher = javax.crypto.Cipher.getInstance("AES/CBC/PKCS5Padding");
            javax.crypto.spec.SecretKeySpec keySpec = new javax.crypto.spec.SecretKeySpec(aesKey, "AES");
            javax.crypto.spec.IvParameterSpec ivSpec = new javax.crypto.spec.IvParameterSpec(
                    Base64.getMimeDecoder().decode(ivB64));

            aesCipher.init(javax.crypto.Cipher.DECRYPT_MODE, keySpec, ivSpec);
            byte[] decodedData = aesCipher.doFinal(Base64.getMimeDecoder().decode(encDataB64));

            return new String(decodedData, StandardCharsets.UTF_8);
        } catch (Exception e) {
            plugin.logInfo("❌ Security: Decryption failed: " + e.getMessage());
            plugin.logInfo("❌ Security: Error handling encrypted response: " + e.getMessage());
            e.printStackTrace();
            return null;
        }
    }

    private String listToJsonArray(String commaSeparated) {
        if (commaSeparated.isEmpty())
            return "[]";
        StringBuilder sb = new StringBuilder("[");
        String[] items = commaSeparated.split(",");
        for (int i = 0; i < items.length; i++) {
            if (i > 0)
                sb.append(",");
            sb.append("\"").append(items[i]).append("\"");
        }
        sb.append("]");
        return sb.toString();
    }

    private void loadPublicKey() {
        try {
            String publicKeyStr = DEFAULT_PUBLIC_KEY;

            if (publicKeyStr.contains("PLACEHOLDER")) {
                plugin.logInfo("⚠️ Security: No valid public key found. Signature validation DISABLED.");
                validationEnabled = false;
                return;
            }

            byte[] keyBytes = Base64.getDecoder().decode(publicKeyStr);
            X509EncodedKeySpec spec = new X509EncodedKeySpec(keyBytes);
            KeyFactory kf = KeyFactory.getInstance("RSA");
            this.publicKey = kf.generatePublic(spec);
            this.validationEnabled = true;
        } catch (Exception e) {
            plugin.logInfo("❌ Security: Failed to load public key: " + e.getMessage());
            validationEnabled = false;
        }
    }

    public boolean verifySignature(String data, String signatureBase64) {
        if (!validationEnabled) {
            return true;
        }

        if ("ENCRYPTED_CHANNEL".equals(signatureBase64)) {
            return true;
        }

        try {
            Signature sign = Signature.getInstance("SHA256withRSA");
            sign.initVerify(publicKey);
            sign.update(data.getBytes(StandardCharsets.UTF_8));

            byte[] signatureBytes = Base64.getDecoder().decode(signatureBase64);
            return sign.verify(signatureBytes);

        } catch (Exception e) {
            plugin.logInfo("❌ Security: Signature verification error: " + e.getMessage());
            return false;
        }
    }

    public boolean verifyTimestamp(long timestamp) {
        if (!validationEnabled) {
            return true;
        }
        long currentTime = System.currentTimeMillis();
        long diff = Math.abs(currentTime - timestamp);
        return diff < 30000;
    }

    public boolean isValidationEnabled() {
        return validationEnabled;
    }

    public void handleEncryptedResponse(org.bukkit.entity.Player player, String jsonMessage) {
        try {
            // Extract ciphertext manually since we don't use a JSON lib
            String tag = "\"ciphertext\":\"";
            int start = jsonMessage.indexOf(tag);
            if (start == -1) {
                plugin.logInfo("❌ Security: Encrypted response missing ciphertext tag from " + player.getName());
                player.kickPlayer("§cSecurity verification failed.");
                return;
            }
            start += tag.length();
            int end = jsonMessage.indexOf("\"", start);
            if (end == -1) {
                plugin.logInfo("❌ Security: Malformed ciphertext JSON from " + player.getName());
                player.kickPlayer("§cSecurity verification failed.");
                return;
            }

            String ciphertext = jsonMessage.substring(start, end);

            // Now decrypt just the ciphertext
            String decryptedData = decrypt(ciphertext);

            if (decryptedData == null) {
                plugin.logInfo("❌ Security: Decryption of encrypted response failed.");
                player.kickPlayer("§cSecurity verification failed.");
                return;
            }

            // Parse the decrypted data:
            // checkId=...|mods=...|resourcePacks=...|shaderPacks=...|nonce=...|innerHmac=...

            String checkId = "unknown";
            String mods = "";
            String resPacks = "";
            String shaders = "";
            String receivedNonce = "";
            String innerHmac = "";

            String[] fields = decryptedData.split("\\|");
            for (String field : fields) {
                if (field.startsWith("checkId="))
                    checkId = field.substring("checkId=".length());
                else if (field.startsWith("mods="))
                    mods = field.substring("mods=".length());
                else if (field.startsWith("resourcePacks="))
                    resPacks = field.substring("resourcePacks=".length());
                else if (field.startsWith("shaderPacks="))
                    shaders = field.substring("shaderPacks=".length());
                else if (field.startsWith("nonce="))
                    receivedNonce = field.substring("nonce=".length());
                else if (field.startsWith("innerHmac="))
                    innerHmac = field.substring("innerHmac=".length());
            }

            // ============================================================
            // LAYER 3 INTEGRITY VERIFICATION
            // ============================================================

            // 1. Inner HMAC is REQUIRED — reject old clients without it
            if (innerHmac.isEmpty()) {
                plugin.logInfo("❌ Security: Missing innerHmac from " + player.getName() + " — client update required");
                player.kickPlayer("§cClient update required. Please install the latest Hidder mod.");
                return;
            }

            // 2. Verify Layer 3 nonce matches the session
            UUID playerId = player.getUniqueId();
            PlayerDataManager.PlayerModCheckData checkData = plugin.getPlayerDataManager()
                    .getPlayerModChecks().get(playerId);

            if (checkData != null && checkData.layer3Nonce != null) {
                if (!checkData.layer3Nonce.equals(receivedNonce)) {
                    plugin.logInfo("❌ Security: Layer 3 nonce mismatch for " + player.getName()
                            + " (expected=" + checkData.layer3Nonce + ", got=" + receivedNonce + ")");
                    player.kickPlayer("§cSecurity verification failed.");
                    return;
                }
            } else if (receivedNonce.isEmpty()) {
                plugin.logInfo("❌ Security: Missing nonce from " + player.getName());
                player.kickPlayer("§cClient update required. Please install the latest Hidder mod.");
                return;
            }

            // 3. Verify inner HMAC — data is everything BEFORE "|innerHmac="
            String dataToVerify = decryptedData;
            int hmacFieldIdx = dataToVerify.indexOf("|innerHmac=");
            if (hmacFieldIdx != -1) {
                dataToVerify = dataToVerify.substring(0, hmacFieldIdx);
            }

            if (!verifyInnerHmac(dataToVerify, innerHmac)) {
                plugin.logInfo("❌ Security: Inner HMAC verification failed for " + player.getName());
                player.kickPlayer("§cSecurity verification failed.");
                return;
            }

            plugin.logInfo("✅ Layer 3 integrity verified for " + player.getName()
                    + " (nonce matched, HMAC valid)");

            // ============================================================
            // Build reconstituted JSON for downstream processing
            // ============================================================

            String modsJson = listToJsonArray(mods);
            String resPacksJson = listToJsonArray(resPacks);
            String shadersJson = listToJsonArray(shaders);

            long currentTimestamp = System.currentTimeMillis();

            StringBuilder reconstitutedJson = new StringBuilder();
            reconstitutedJson.append("{\"messageType\":\"RESPONSE_MODLIST\",");
            reconstitutedJson.append("\"modId\":\"hidder\",");
            reconstitutedJson.append("\"version\":\"1.21.11\",");
            reconstitutedJson.append("\"checkId\":\"").append(checkId).append("\",");
            reconstitutedJson.append("\"mods\":").append(modsJson).append(",");
            reconstitutedJson.append("\"resourcePacks\":").append(resPacksJson).append(",");
            reconstitutedJson.append("\"shaderPacks\":").append(shadersJson).append(",");

            reconstitutedJson.append("\"signature\":\"ENCRYPTED_CHANNEL\",");
            reconstitutedJson.append("\"timestamp\":").append(currentTimestamp);

            reconstitutedJson.append("}");

            plugin.handleModListResponse(player, reconstitutedJson.toString());

        } catch (Exception e) {
            plugin.logInfo("❌ Security: Error handling encrypted response: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Verify the inner HMAC of decrypted modlist data using the shared secret.
     */
    private boolean verifyInnerHmac(String data, String receivedHmac) {
        if (receivedHmac == null || receivedHmac.isEmpty()) {
            return false;
        }
        try {
            javax.crypto.Mac mac = javax.crypto.Mac.getInstance("HmacSHA256");
            javax.crypto.spec.SecretKeySpec keySpec = new javax.crypto.spec.SecretKeySpec(
                    HMAC_SECRET.getBytes(StandardCharsets.UTF_8), "HmacSHA256");
            mac.init(keySpec);
            byte[] hmacBytes = mac.doFinal(data.getBytes(StandardCharsets.UTF_8));
            String expectedHmac = Base64.getEncoder().encodeToString(hmacBytes);
            return expectedHmac.equals(receivedHmac);
        } catch (Exception e) {
            plugin.logInfo("❌ Security: Inner HMAC computation error: " + e.getMessage());
            return false;
        }
    }

    private String extractJsonValue(String json, String key) {
        String searchKey = "\"" + key + "\":\"";
        int startIndex = json.indexOf(searchKey);
        if (startIndex != -1) {
            startIndex += searchKey.length();
            int endIndex = json.indexOf("\"", startIndex);
            if (endIndex != -1) {
                return json.substring(startIndex, endIndex);
            }
        }
        searchKey = "\"" + key + "\":";
        startIndex = json.indexOf(searchKey);
        if (startIndex != -1) {
            startIndex += searchKey.length();
            int braceCount = 0;
            int bracketCount = 0;
            for (int i = startIndex; i < json.length(); i++) {
                char c = json.charAt(i);
                if (c == '{')
                    braceCount++;
                else if (c == '}')
                    braceCount--;
                else if (c == '[')
                    bracketCount++;
                else if (c == ']')
                    bracketCount--;

                if ((c == ',' || c == '}') && braceCount == 0 && bracketCount == 0) {
                    return json.substring(startIndex, i).trim();
                }
            }
            return json.substring(startIndex).trim();
        }
        return "";
    }

    // ============================================================
    // Layer 0: Pre-Login Beacon Cache Methods
    // ============================================================

    /**
     * Add a verified IP to the beacon cache
     * 
     * @param ip The IP address
     * @return true if added, false if rate limited or cache full
     */
    public boolean addVerifiedIP(String ip) {
        if (ip == null || ip.isEmpty()) {
            return false;
        }

        long now = System.currentTimeMillis();

        // Check rate limit
        Long lastPing = rateLimitMap.get(ip);
        if (lastPing != null && (now - lastPing) < BEACON_RATE_LIMIT_MS) {
            return false; // Rate limited, silently ignore
        }

        // Update rate limit timestamp
        rateLimitMap.put(ip, now);

        // Check size limit - remove oldest entries if needed
        if (verifiedIPs.size() >= BEACON_MAX_SIZE) {
            cleanupExpiredBeacons();

            // If still full, remove oldest
            if (verifiedIPs.size() >= BEACON_MAX_SIZE) {
                removeOldestBeacon();
            }
        }

        // Add to cache
        verifiedIPs.put(ip, now + BEACON_EXPIRY_MS);
        return true;
    }

    /**
     * Check if an IP is verified (has a valid beacon)
     */
    public boolean isIPVerified(String ip) {
        if (ip == null || ip.isEmpty()) {
            return false;
        }

        Long expiry = verifiedIPs.get(ip);
        if (expiry == null) {
            return false;
        }

        // Check if expired
        if (System.currentTimeMillis() > expiry) {
            verifiedIPs.remove(ip);
            return false;
        }

        return true;
    }

    /**
     * Remove an IP from beacon cache (one-time use after login)
     */
    public void removeVerifiedIP(String ip) {
        if (ip != null) {
            verifiedIPs.remove(ip);
        }
    }

    /**
     * Clean up expired beacon entries
     */
    public void cleanupExpiredBeacons() {
        long now = System.currentTimeMillis();

        // Cleanup verified IPs
        Iterator<Map.Entry<String, Long>> it = verifiedIPs.entrySet().iterator();
        while (it.hasNext()) {
            if (now > it.next().getValue()) {
                it.remove();
            }
        }

        // Cleanup rate limit map (entries older than rate limit window)
        Iterator<Map.Entry<String, Long>> rateLimitIt = rateLimitMap.entrySet().iterator();
        while (rateLimitIt.hasNext()) {
            if (now - rateLimitIt.next().getValue() > BEACON_RATE_LIMIT_MS * 2) {
                rateLimitIt.remove();
            }
        }
    }

    private void removeOldestBeacon() {
        String oldestIP = null;
        long oldestTime = Long.MAX_VALUE;

        for (Map.Entry<String, Long> entry : verifiedIPs.entrySet()) {
            long addedTime = entry.getValue() - BEACON_EXPIRY_MS;
            if (addedTime < oldestTime) {
                oldestTime = addedTime;
                oldestIP = entry.getKey();
            }
        }

        if (oldestIP != null) {
            verifiedIPs.remove(oldestIP);
        }
    }

    // ============================================================
    // Layer 1: Player Freeze Methods
    // ============================================================

    /**
     * Freeze a player (block all actions during verification)
     */
    public void freezePlayer(UUID playerId) {
        frozenPlayers.add(playerId);
    }

    /**
     * Unfreeze a player (allow all actions after verification)
     */
    public void unfreezePlayer(UUID playerId) {
        frozenPlayers.remove(playerId);
    }

    /**
     * Check if a player is frozen
     */
    public boolean isFrozen(UUID playerId) {
        return frozenPlayers.contains(playerId);
    }

    /**
     * Unfreeze all players (cleanup on disable)
     */
    public void unfreezeAll() {
        frozenPlayers.clear();
    }

    // ============================================================
    // Freeze Event Handlers
    // ============================================================

    @EventHandler(priority = EventPriority.LOWEST)
    public void onPlayerMove(PlayerMoveEvent event) {
        if (isFrozen(event.getPlayer().getUniqueId())) {
            // Allow head rotation but prevent position change
            if (event.getFrom().getX() != event.getTo().getX() ||
                    event.getFrom().getY() != event.getTo().getY() ||
                    event.getFrom().getZ() != event.getTo().getZ()) {
                event.setTo(event.getFrom());
            }
        }
    }

    @EventHandler(priority = EventPriority.LOWEST)
    public void onBlockBreak(BlockBreakEvent event) {
        if (isFrozen(event.getPlayer().getUniqueId())) {
            event.setCancelled(true);
        }
    }

    @EventHandler(priority = EventPriority.LOWEST)
    public void onBlockPlace(BlockPlaceEvent event) {
        if (isFrozen(event.getPlayer().getUniqueId())) {
            event.setCancelled(true);
        }
    }

    @EventHandler(priority = EventPriority.LOWEST)
    public void onPlayerInteract(PlayerInteractEvent event) {
        if (isFrozen(event.getPlayer().getUniqueId())) {
            event.setCancelled(true);
        }
    }

    @EventHandler(priority = EventPriority.LOWEST)
    public void onPlayerCommand(PlayerCommandPreprocessEvent event) {
        if (isFrozen(event.getPlayer().getUniqueId())) {
            event.setCancelled(true);
        }
    }

    @EventHandler(priority = EventPriority.LOWEST)
    public void onPlayerDropItem(PlayerDropItemEvent event) {
        if (isFrozen(event.getPlayer().getUniqueId())) {
            event.setCancelled(true);
        }
    }

    @EventHandler(priority = EventPriority.LOWEST)
    public void onEntityDamage(EntityDamageEvent event) {
        if (event.getEntity() instanceof Player) {
            Player player = (Player) event.getEntity();
            if (isFrozen(player.getUniqueId())) {
                event.setCancelled(true);
            }
        }
    }

    @EventHandler(priority = EventPriority.LOWEST)
    public void onEntityDamageByEntity(EntityDamageByEntityEvent event) {
        if (event.getDamager() instanceof Player) {
            Player player = (Player) event.getDamager();
            if (isFrozen(player.getUniqueId())) {
                event.setCancelled(true);
            }
        }
    }

    @EventHandler(priority = EventPriority.LOWEST)
    public void onServerListPing(PaperServerListPingEvent event) {
        if (publicKey == null) {
            return;
        }

        String hostname = event.getClient().getVirtualHost() != null
                ? event.getClient().getVirtualHost().getHostString()
                : null;

        if (hostname == null || !hostname.contains("\0" + BEACON_PREFIX)) {
            return;
        }

        int beaconStart = hostname.indexOf("\0" + BEACON_PREFIX);
        String beaconData = hostname.substring(beaconStart + 1 + BEACON_PREFIX.length());

        String[] parts = beaconData.split(":", 2);
        if (parts.length != 2) {
            return;
        }

        try {
            long timestamp = Long.parseLong(parts[0]);
            String signatureB64 = parts[1];

            long now = System.currentTimeMillis();
            if (Math.abs(now - timestamp) > 30000) {
                return;
            }

            if (!verifyBeaconSignature(String.valueOf(timestamp), signatureB64)) {
                return;
            }

            InetSocketAddress clientAddress = event.getClient().getAddress();
            String clientIP = clientAddress.getAddress().getHostAddress();

            if (addVerifiedIP(clientIP)) {
                plugin.logInfo("🔐 Layer 0: Beacon verified for IP " + clientIP);
            }

        } catch (NumberFormatException e) {
        }
    }

    @EventHandler(priority = EventPriority.LOWEST)
    public void onAsyncPlayerPreLogin(AsyncPlayerPreLoginEvent event) {
        // TEMPORARILY DISABLED: Layer 0 mixin not compatible with 1.21.11
        // Uncomment this code once ConnectScreenMixin is fixed
        return;

        /*
         * if (configManager == null || !configManager.isModVerificationEnabled()) {
         * return;
         * }
         * 
         * if (!LAYER_0_ENABLED) {
         * return;
         * }
         * 
         * String playerIP = event.getAddress().getHostAddress();
         * String playerName = event.getName();
         * 
         * if (!isIPVerified(playerIP)) {
         * plugin.logInfo("🚫 Layer 0: Blocked login from unverified IP " + playerIP +
         * " (" + playerName + ")");
         * event.disallow(
         * AsyncPlayerPreLoginEvent.Result.KICK_OTHER,
         * "§cConnection verification failed.\n§7Please install the required Hidder mod."
         * );
         * return;
         * }
         * 
         * removeVerifiedIP(playerIP);
         * plugin.logInfo("✅ Layer 0: Pre-login verified for " + playerName + " (" +
         * playerIP + ")");
         */
    }

    private boolean verifyBeaconSignature(String data, String signatureBase64) {
        try {
            Signature sign = Signature.getInstance("SHA256withRSA");
            sign.initVerify(publicKey);
            sign.update(data.getBytes());

            byte[] signatureBytes = Base64.getDecoder().decode(signatureBase64);
            return sign.verify(signatureBytes);
        } catch (Exception e) {
            return false;
        }
    }

    public void setConfigManager(ConfigManager configManager) {
        this.configManager = configManager;
    }
}
